services:
  - type: web
    name: portfolio-neon
    runtime: docker
    plan: free
    region: frankfurt
    healthCheckPath: /up
    envVars:
      - key: APP_NAME
        value: Portfolio Neon
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        value: base64:rZWM2jlnL9P2jky+g1wHbPygurTzWwHVwVmejHjjK8M=
      - key: APP_LOCALE
        value: fr
      - key: APP_FALLBACK_LOCALE
        value: fr
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: info
      - key: DB_CONNECTION
        value: sqlite
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: FILESYSTEM_DISK
        value: local
